// beauty_localizer.dart
// Mirrors iOS StringLocalizer.swift + Localizable.strings

const Map<String, String> _enStrings = {
  // Groups
  'beauty_group_beauty': 'Beauty',
  'beauty_group_filter': 'Filter',
  'beauty_group_makeup': 'Makeup',
  'beauty_group_sticker': 'Sticker',
  // Settings
  'beauty_setting_saved_info': 'Beauty settings saved',
  'beauty_setting_reseted_info': 'Beauty settings reseted',
  'beauty_setting_beauty': 'Beauty',
  'beauty_setting_save': 'Save',
  'beauty_setting_reset': 'Reset',
  'beauty_setting_join': 'Join',
  'beauty_setting_leave': 'Leave',
  'beauty_setting_switch_camera': 'Switch',
  // Common
  'beauty_effect_none': 'None',
  'beauty_effect_enable': 'Enable',
  'beauty_effect_disable': 'Disable',
  'beauty_effect_reset': 'Reset',
  // Skin beauty
  'beauty_effect_smoothness': 'Smooth',
  'beauty_effect_lightness': 'Whiten',
  'beauty_effect_redness': 'Rosy',
  'beauty_effect_contrast_strength': 'Clarity',
  'beauty_effect_sharpness': 'Sharpen',
  'beauty_effect_eye_pouch': 'Dark\nCircles',
  'beauty_effect_brighten_eye': 'Eye\nBrighten',
  'beauty_effect_whiten_teeth': 'Teeth\nWhitening',
  'beauty_effect_nasolabial_fold': 'Smile\nLines',
  'beauty_effect_temperature': 'Temp',
  'beauty_effect_hue': 'Tint',
  'beauty_effect_saturation': 'Saturation',
  'beauty_effect_brightness': 'Brightness',
  // Face shape
  'beauty_face_shape_face_contour': 'Face\nSlim',
  'beauty_face_shape_mandible': 'V-Face',
  'beauty_face_shape_chin': 'Chin',
  'beauty_face_shape_cheek': 'Jaw',
  'beauty_face_shape_cheekbone': 'Cheek\nBones',
  'beauty_face_shape_face_length': 'Face\nLength',
  'beauty_face_shape_face_width': 'Face\nWidth',
  'beauty_face_shape_fore_head': 'Hairline',
  'beauty_face_shape_head_scale': 'Head\nSize',
  'beauty_face_shape_nose_width': 'Nose\nSlim',
  'beauty_face_shape_nose_root': 'Radix',
  'beauty_face_shape_nose_bridge': 'Nose\nBridge',
  'beauty_face_shape_nose_tip': 'Nose\nTip',
  'beauty_face_shape_nose_wing': 'Nose\nWing',
  'beauty_face_shape_nose_length': 'Nose\nLength',
  'beauty_face_shape_nose_general': 'Nose\nSize',
  'beauty_face_shape_eye_scale': 'Eye\nSize',
  'beauty_face_shape_eye_distance': 'Eye\nDist',
  'beauty_face_shape_eye_lid': 'Lower\nEyelid',
  'beauty_face_shape_inner_corner': 'Inner\nCorner',
  'beauty_face_shape_outer_corner': 'Outer\nCorner',
  'beauty_face_shape_eye_position': 'Eye\nPos',
  'beauty_face_shape_eye_pupils': 'Pupil',
  'beauty_face_shape_mouth_smile': 'Smile',
  'beauty_face_shape_mouth_lip': 'Lip\nThick',
  'beauty_face_shape_mouth_scale': 'Mouth\nSize',
  'beauty_face_shape_mouth_position': 'Philtrum',
  'beauty_face_shape_eyebrow_thickness': 'Brow\nThick',
  'beauty_face_shape_eyebrow_position': 'Brow\nLift',
  // Filters
  'beauty_filter_serene': 'Serene',
  'beauty_filter_urban': 'Urban',
  'beauty_filter_glow': 'Glow',
  'beauty_filter_gilt': 'Gilt',
  'beauty_filter_cream': 'Cream',
  'beauty_filter_latte': 'Latte',
  'beauty_filter_summer': 'Summer',
  'beauty_filter_daily': 'Daily',
  'beauty_filter_gentleman': 'Gentleman',
  'beauty_filter_vanilla': 'Vanilla',
  'beauty_filter_bright': 'Bright',
  'beauty_filter_peach': 'Peach',
  'beauty_filter_ink': 'Ink',
  'beauty_filter_film': 'Film',
  'beauty_filter_sunny': 'Sunny',
  'beauty_filter_comic': 'Comic',
  'beauty_filter_dreamy': 'Dreamy',
  'beauty_filter_cotton': 'Cotton',
  'beauty_filter_soda': 'Soda',
  'beauty_filter_moonlight': 'Moonlight',
  'beauty_filter_white_tea': 'White\nTea',
  'beauty_filter_tranquil': 'Tranquil',
  'beauty_filter_insta_style': 'Ins',
  'beauty_filter_street': 'Street',
  'beauty_filter_puff': 'Puff',
  'beauty_filter_collection': 'Collection',
  'beauty_filter_salty': 'Salty',
  'beauty_filter_texture': 'Texture',
  'beauty_filter_colorful': 'Colorful',
  'beauty_filter_snow': 'Snow',
  'beauty_filter_blush': 'Blush',
  'beauty_filter_nostalgia': 'Nostalgia',
  'beauty_filter_caramel': 'Caramel',
  'beauty_filter_tipsy': 'Tipsy',
  'beauty_filter_lavender': 'Lavender',
  'beauty_filter_rouge': 'Rouge',
  'beauty_filter_misty': 'Misty',
  // Makeup
  'beauty_makeup_young': 'Young',
  'beauty_makeup_mature': 'Mature',
  'beauty_makeup_aura': 'Aura',
  'beauty_makeup_natural': 'Natural',
  'beauty_makeup_graceful': 'Graceful',
  'beauty_makeup_charm': 'Charm',
  'beauty_makeup_perky': 'Perky',
  'beauty_makeup_maiden': 'Maiden',
  'beauty_makeup_insight': 'Insight',
  'beauty_makeup_misty': 'Misty',
  // Stickers
  'beauty_sticker_christmas': 'Christmas',
  'beauty_sticker_squid': 'Squid',
  'beauty_sticker_piggy': 'Piggy',
  'beauty_sticker_long_cat': 'Long Cat',
  'beauty_sticker_hairhoop': 'Hairhoop',
  'beauty_sticker_relax_time': 'Relax',
  'beauty_sticker_cartoon_cat': 'Cartoon Cat',
  'beauty_sticker_butterfly': 'Butterfly',
  'beauty_sticker_brush': 'Brush',
  'beauty_sticker_cyber_glass': 'Cyber Glass',
  'beauty_sticker_neon_tiara': 'Neon Tiara',
  'beauty_sticker_love_glass': 'Love Glass',
};

const Map<String, String> _zhStrings = {
  'beauty_group_beauty': '美颜',
  'beauty_group_filter': '滤镜',
  'beauty_group_makeup': '美妆',
  'beauty_group_sticker': '贴纸',
  'beauty_setting_saved_info': '已保存',
  'beauty_setting_reseted_info': '已重置',
  'beauty_setting_beauty': '美颜',
  'beauty_setting_save': '保存',
  'beauty_setting_reset': '重置',
  'beauty_setting_join': '加入频道',
  'beauty_setting_leave': '离开频道',
  'beauty_setting_switch_camera': '切换',
  'beauty_effect_none': '无',
  'beauty_effect_enable': '已开启',
  'beauty_effect_disable': '关闭',
  'beauty_effect_reset': '重置',
  'beauty_effect_smoothness': '磨皮',
  'beauty_effect_lightness': '美白',
  'beauty_effect_redness': '红润',
  'beauty_effect_contrast_strength': '清晰度',
  'beauty_effect_sharpness': '锐化',
  'beauty_effect_eye_pouch': '去黑眼圈',
  'beauty_effect_brighten_eye': '亮眼',
  'beauty_effect_whiten_teeth': '白牙',
  'beauty_effect_nasolabial_fold': '去法令纹',
  'beauty_effect_temperature': '色温',
  'beauty_effect_hue': '色调',
  'beauty_effect_saturation': '饱和度',
  'beauty_effect_brightness': '亮度',
  'beauty_face_shape_face_contour': '瘦脸',
  'beauty_face_shape_mandible': 'v脸',
  'beauty_face_shape_chin': '瘦下巴',
  'beauty_face_shape_cheek': '下颌线',
  'beauty_face_shape_cheekbone': '瘦颧骨',
  'beauty_face_shape_face_length': '长脸',
  'beauty_face_shape_face_width': '窄脸',
  'beauty_face_shape_fore_head': '发际线',
  'beauty_face_shape_head_scale': '小头',
  'beauty_face_shape_nose_width': '瘦鼻',
  'beauty_face_shape_nose_root': '山根',
  'beauty_face_shape_nose_bridge': '鼻梁',
  'beauty_face_shape_nose_tip': '鼻尖',
  'beauty_face_shape_nose_wing': '鼻翼',
  'beauty_face_shape_nose_length': '长鼻',
  'beauty_face_shape_nose_general': '鼻综合',
  'beauty_face_shape_eye_scale': '大眼',
  'beauty_face_shape_eye_distance': '眼距',
  'beauty_face_shape_eye_lid': '眼睑下至',
  'beauty_face_shape_inner_corner': '内眼角',
  'beauty_face_shape_outer_corner': '外眼角',
  'beauty_face_shape_eye_position': '眼移动',
  'beauty_face_shape_eye_pupils': '瞳孔',
  'beauty_face_shape_mouth_smile': '微笑唇',
  'beauty_face_shape_mouth_lip': '丰唇',
  'beauty_face_shape_mouth_scale': '嘴型',
  'beauty_face_shape_mouth_position': '缩人中',
  'beauty_face_shape_eyebrow_thickness': '眉粗细',
  'beauty_face_shape_eyebrow_position': '眉上下',
  'beauty_filter_serene': '沉稳',
  'beauty_filter_urban': '都市',
  'beauty_filter_glow': '流光',
  'beauty_filter_gilt': '流金',
  'beauty_filter_cream': '奶油',
  'beauty_filter_latte': '拿铁',
  'beauty_filter_summer': '柠夏',
  'beauty_filter_daily': '日常',
  'beauty_filter_gentleman': '绅士',
  'beauty_filter_vanilla': '香草',
  'beauty_filter_bright': '白瓷',
  'beauty_filter_peach': '白桃',
  'beauty_filter_ink': '苍墨',
  'beauty_filter_film': '胶片',
  'beauty_filter_sunny': '霁晴',
  'beauty_filter_comic': '漫画',
  'beauty_filter_dreamy': '梦幻',
  'beauty_filter_cotton': '棉绒',
  'beauty_filter_soda': '苏打',
  'beauty_filter_moonlight': '月白',
  'beauty_filter_white_tea': '白茶',
  'beauty_filter_tranquil': '沉谧',
  'beauty_filter_insta_style': 'ins风',
  'beauty_filter_street': '老街',
  'beauty_filter_puff': '泡芙',
  'beauty_filter_collection': '私藏',
  'beauty_filter_salty': '盐汽水',
  'beauty_filter_texture': '质感',
  'beauty_filter_colorful': '气色',
  'beauty_filter_snow': '初雪',
  'beauty_filter_blush': '粉霞',
  'beauty_filter_nostalgia': '怀旧',
  'beauty_filter_caramel': '焦糖',
  'beauty_filter_tipsy': '微醺',
  'beauty_filter_lavender': '薰衣草',
  'beauty_filter_rouge': '胭脂',
  'beauty_filter_misty': '氤氲',
  'beauty_makeup_young': '学妹妆',
  'beauty_makeup_mature': '学姐妆',
  'beauty_makeup_aura': '气质妆',
  'beauty_makeup_natural': '白皙妆',
  'beauty_makeup_graceful': '优雅妆',
  'beauty_makeup_charm': '粉晕妆',
  'beauty_makeup_perky': '俏皮妆',
  'beauty_makeup_maiden': '少女妆',
  'beauty_makeup_insight': '深邃妆',
  'beauty_makeup_misty': '氤氲妆',
  'beauty_sticker_christmas': '圣诞节',
  'beauty_sticker_squid': '章鱼',
  'beauty_sticker_piggy': '猪可爱',
  'beauty_sticker_long_cat': '辫子猫',
  'beauty_sticker_hairhoop': '粉色发箍',
  'beauty_sticker_relax_time': '没有烦恼',
  'beauty_sticker_cartoon_cat': '卡通猫',
  'beauty_sticker_butterfly': '蝴蝶',
  'beauty_sticker_brush': '粉刷时光',
  'beauty_sticker_cyber_glass': '赛博眼镜',
  'beauty_sticker_neon_tiara': '霓虹皇冠',
  'beauty_sticker_love_glass': '爱心眼镜',
};

/// Global language setting for beauty UI.
/// Set this before showing the beauty panel.
/// Supported: 'en' (default), 'zh', or any language code you add strings for.
class BeautyLocalizer {
  BeautyLocalizer._();

  static String _lang = 'en';

  static String get lang => _lang;

  static void setLang(String lang) {
    _lang = lang;
  }
}

/// Localize a beauty string key using the global language setting.
/// Falls back to English if the key is not found in the current locale.
String beautyLocalized(String key) {
  final lang = BeautyLocalizer.lang;
  final Map<String, String> map;
  if (lang == 'zh') {
    map = _zhStrings;
  } else {
    map = _enStrings;
  }
  return map[key] ?? _enStrings[key] ?? key;
}
